Update example-snyk-full.yml

diff --git a/.github/workflows/example-snyk-full.yml b/.github/workflows/example-snyk-full.yml
--- a/.github/workflows/example-snyk-full.yml
+++ b/.github/workflows/example-snyk-full.yml
@@ -37,23 +37,30 @@ jobs:
         uses: snyk/actions/setup@master
         # For Snyk Open Source you must first set up the development environment for your application's dependencies
         # For example for Node
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16
+        #- uses: actions/setup-node@v3
+        #  with:
+        #    node-version: 16
         env:
           # In order to use the Snyk Action you will need to have a Snyk API token.
           # More details in https://github.com/snyk/actions#getting-your-snyk-token
           # or you can signup for free at https://snyk.io/login
           SNYK_TOKEN: ${{ secrets.SNYK_AUTH }}
+        # Runs Snyk Open Source (SCA) analysis. Use || true to not fail the pipeline
       - name: Snyk Open Source test
         run: snyk test || true
+        # Runs Snyk Code (SAST) analysis and uploads results into GitHub. Use || true to not fail the pipeline      
       - name: Snyk Code test   
-        # Runs Snyk Code (SAST) analysis and uploads results into GitHub. || true makes it not fail
-        continue-on-error: true
-        run: snyk code test --sarif > snyk-code.sarif
+        run: snyk code test --sarif > snyk-code.sarif || true
+        # Runs Snyk Infrastructure as Code (IaC) analysis. Use || true to not fail the pipeline.
       - name: Snyk IaC test
-        # Runs Snyk Infrastructure as Code (IaC) analysis. || true makes it not fail 
-        run: snyk iac test || true 
+        run: snyk iac test || true
+        # Build the docker image for testing
+      - name: Build a Docker image
+        run: docker build -t your/image-to-test .
+        # Runs Snyk Container (Container and SCA) analysis. Use || true to not fail the pipeline
+      - name: Snyk Container test
+        run: snyk container test your/image-to-test --file=Dockerfile || true
+        # Push the Snyk Code results into GitHub Code Scanning tab
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
