Update example-snyk-full.yml

diff --git a/.github/workflows/example-snyk-full.yml b/.github/workflows/example-snyk-full.yml
--- a/.github/workflows/example-snyk-full.yml
+++ b/.github/workflows/example-snyk-full.yml
@@ -5,7 +5,7 @@
 
 # A sample workflow which sets up Snyk to analyze the full Snyk platform (Snyk Open Source, Snyk Code, Snyk Container and Snyk Infrastructure as Code)
 # This includes SCA, SAST, Container and IaC scanning
-# The results are then uploaded to GitHub Security Code Scanning
+# The results of Snyk Code are then uploaded to GitHub Security Code Scanning
 #
 # For more examples, including how to limit scans to only high-severity issues
 # and fail PR checks, see https://github.com/snyk/actions/
@@ -16,7 +16,6 @@ on:
   push:
     branches: [ master ]
   pull_request:
-    # The branches below must be a subset of the branches above
     branches: [ master ]
   workflow_dispatch:
 
@@ -35,7 +34,6 @@ jobs:
       - name: Set up Snyk CLI to check for security issues
         # Snyk can be used to break the build when it detects security issues.
         # In this case we want to upload the issues to GitHub Code Scanning
-        continue-on-error: true
         uses: snyk/actions/setup@master
         # For Snyk Open Source you must first set up the development environment for your application's dependencies
         # For example for Node
@@ -47,11 +45,16 @@ jobs:
           # More details in https://github.com/snyk/actions#getting-your-snyk-token
           # or you can signup for free at https://snyk.io/login
           SNYK_TOKEN: ${{ secrets.SNYK_AUTH }}
+      - name: Snyk Open Source test
+        run: snyk test || true
       - name: Snyk Code test   
-        run: snyk code test --sarif > snyk-code.sarif || true # 
+        # Runs Snyk Code (SAST) analysis and uploads results into GitHub. || true makes it not fail
+        continue-on-error: true
+        run: snyk code test --sarif > snyk-code.sarif
       - name: Snyk IaC test
-        run: snyk iac test --sarif > snyk-iac.sarif || true
+        # Runs Snyk Infrastructure as Code (IaC) analysis. || true makes it not fail 
+        run: snyk iac test || true 
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
-          sarif_file: snyk-code.sarif, snyk-iac.sarif
+          sarif_file: snyk-code.sarif
